Implement simple quert selector
philip-peterson/rust-rdom pull request #16
Opened 2021-04-06 00:34 UTC by maksimil

This implementation is really basic, but can be scaled. However it returns Arc<dyn AnyNode> instead of Arc<dyn AnyElement>. Currently I don't think such downcasting is supported.

Closes #1

2021-04-06 01:00 UTC, maksimil commented
So I just created [maksimil/add_arc_weak_prelude](https://github.com/philip-peterson/rust-rdom/tree/maksimil/add_arc_weak_prelude), can I just merge that branch into here and then close with this PR both #16 and #13? That branch is like 1 commit long, is it worth opening a separate PR?

2021-04-06 02:11 UTC, philip-peterson commented
@maksimil I just merged your branch, in the future it's preferred to open a PR. Doesn't need to be fancy, I'm deliberately shying away from checklists because I think they add undue burden. Just a simple one-sentence description should be fine.

2021-04-06 02:40 UTC, philip-peterson requested changes

2021-04-06 02:40 UTC, philip-peterson commented on src/node/mod.rs
> +    fn query_selector(&self, selector: &str) -> Result<Option<Arc<dyn AnyNode>>, DomError>;
So weirdly, not all nodes support `querySelector` (for example `TextNode`s do not). Looking at MDN, it seems that the following support it:
* Document
* Element
* ParentNode (which we don't really have yet)
* DocumentFragment (not implemented yet)

So, I think next action item would be to move it from `AnyNode` to `AnyElement` and add it to `Document` (note that `Document`.

2021-04-06 02:40 UTC, philip-peterson commented on src/node/mod.rs
> +        write!(f, "<{} />", self.tag_name())
Nice. 👍

2021-04-06 02:40 UTC, philip-peterson commented on src/node/mod.rs
> +                    fn tag_name(&self) -> String {
This would be another good thing to remove; Nodes for the most part don't have `tagName`s.

2021-04-06 02:40 UTC, philip-peterson commented on src/node/element.rs
> +                        String::from($tag)
Nit:

```suggestion
                        $tag.to_string()
```

For code style 💇

2021-04-06 02:40 UTC, philip-peterson commented on src/node/query_selector.rs
> +        // allow unsafe code, @philip-peterson
While I appreciate the idea, let's save optimizations for later down the road, especially ones that use `unsafe`. I strongly expect that the string operations will not be a significant slowdown.

2021-04-06 02:40 UTC, philip-peterson commented on src/node/mod.rs
> +pub mod query_selector;
Let's keep this one non-`pub`, since there's no reason an `rdom` user would need to invoke the functionality directly.

2021-04-06 02:40 UTC, philip-peterson commented on src/tests.rs
> +    assert!(Arc::ptr_eq(&qbody, &body));
Oh that's cool! Didn't know about this method of `Arc`.

2021-04-06 02:40 UTC, philip-peterson commented
@maksimil Looks good, nice first big PR! Just a few nitpicks, other than that I think this is good to merge.

2021-04-07 22:13 UTC, maksimil commented on src/node/query_selector.rs
> +        // allow unsafe code, @philip-peterson
Ok, I wanted to use them not really for optimization, but because I thought it would be funny

2021-04-11 01:41 UTC, maksimil commented on src/node/mod.rs
> +    fn query_selector(&self, selector: &str) -> Result<Option<Arc<dyn AnyNode>>, DomError>;
Because the solution to this problem requires casting of trait objects, I think that querySelector can be implemented for all the nodes. This shouldn't affect anything, because nodes that don't support it don't have a lot of child nodes. The paths can be cut off with a node type check when #20 is merged.

2021-04-11 07:57 UTC, philip-peterson commented
I think this might be okay. Could you resolve the remaining merge conflicts? By the time it's ready, I may have the macro rewrite done, but either way it will be good to have this mergeable so that we can easily rebase it.

2021-04-19 11:05 UTC, maksimil commented
Closing this PR because the backend fundamentally changed and it's easier to start again for this branch.

2021-04-19 11:05 UTC, closed without merging